/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MonthlySummary from '../model/MonthlySummary';

/**
* TransactionSummary service.
* @module api/TransactionSummaryApi
* @version 2.1.0
*/
export default class TransactionSummaryApi {

    /**
    * Constructs a new TransactionSummaryApi. 
    * @alias module:api/TransactionSummaryApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the listSummary operation.
     * @callback module:api/TransactionSummaryApi~listSummaryCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/MonthlySummary>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List account summaries
     * Retrieve account summaries and provide a sum for incoming and outgoing transactions.
     * @param {String} accessId The **accessId** for which to list the summaries
     * @param {String} accountId The **accountId** for which to list the summaries
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Optional — limit the number of returned summary entries
     * @param {Number} opts.offset Optional — skip the first **offset** summary entries in the result
     * @param {String} opts.from Optional — only return summary entries later than **from**; an         ISO8601 Date (2014-11-17)
     * @param {String} opts.to Optional — only return summary entries prior or equal to         **to**; an ISO8601 Date
     * @param {module:api/TransactionSummaryApi~listSummaryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/MonthlySummary>}
     */
    listSummary(accessId, accountId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'accessId' is set
      if (accessId === undefined || accessId === null) {
        throw new Error("Missing the required parameter 'accessId' when calling listSummary");
      }

      // verify the required parameter 'accountId' is set
      if (accountId === undefined || accountId === null) {
        throw new Error("Missing the required parameter 'accountId' when calling listSummary");
      }


      let pathParams = {
        'accessId': accessId,
        'accountId': accountId
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset'],
        'from': opts['from'],
        'to': opts['to']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [MonthlySummary];

      return this.apiClient.callApi(
        '/accesses/{accessId}/accounts/{accountId}/transactionsummaries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
