/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import InputFieldDescription from './InputFieldDescription';





/**
* The AccessDescription model module.
* @module model/AccessDescription
* @version 2.1.0
*/
export default class AccessDescription {
    /**
    * Constructs a new <code>AccessDescription</code>.
    * @alias module:model/AccessDescription
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AccessDescription</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccessDescription} obj Optional instance to populate.
    * @return {module:model/AccessDescription} The populated <code>AccessDescription</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccessDescription();

            
            
            

            if (data.hasOwnProperty('infoText')) {
                obj['infoText'] = ApiClient.convertToType(data['infoText'], 'String');
            }
            if (data.hasOwnProperty('fieldDescriptions')) {
                obj['fieldDescriptions'] = ApiClient.convertToType(data['fieldDescriptions'], [InputFieldDescription]);
            }
        }
        return obj;
    }

    /**
    * Information text by the provider as a description for required user actions during the account setup (e.g.,   \"Provided your financial institution has not given you a separate username, please enter  your account number as your username. Depending on your financial institution,  additional information such as a customer number can be entered. Most of the time  entering this information is optional.\")
    * @member {String} infoText
    */
    infoText = undefined;
    /**
    * Information to describe and facilitate validation of an access.
    * @member {Array.<module:model/InputFieldDescription>} fieldDescriptions
    */
    fieldDescriptions = undefined;








}


