/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AdditionalInformation model module.
* @module model/AdditionalInformation
* @version 2.1.0
*/
export default class AdditionalInformation {
    /**
    * Constructs a new <code>AdditionalInformation</code>.
    * @alias module:model/AdditionalInformation
    * @class
    * @param id {String}
    * @param type {String} Discriminator for subtypes. At the moment only `Category` and `Contractor` are supported.
    */

    constructor(id, type) {
        

        
        

        this['id'] = id;this['type'] = type;

        
    }

    /**
    * Constructs a <code>AdditionalInformation</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AdditionalInformation} obj Optional instance to populate.
    * @return {module:model/AdditionalInformation} The populated <code>AdditionalInformation</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdditionalInformation();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} type
    */
    type = undefined;








}


