/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Amount from './Amount';





/**
* The Asset model module.
* @module model/Asset
* @version 2.1.0
*/
export default class Asset {
    /**
    * Constructs a new <code>Asset</code>.
    * @alias module:model/Asset
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Asset</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Asset} obj Optional instance to populate.
    * @return {module:model/Asset} The populated <code>Asset</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Asset();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('wkn')) {
                obj['wkn'] = ApiClient.convertToType(data['wkn'], 'String');
            }
            if (data.hasOwnProperty('isin')) {
                obj['isin'] = ApiClient.convertToType(data['isin'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('priceType')) {
                obj['priceType'] = ApiClient.convertToType(data['priceType'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('amountAltCurr')) {
                obj['amountAltCurr'] = Amount.constructFromObject(data['amountAltCurr']);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} wkn
    */
    wkn = undefined;
    /**
    * @member {String} isin
    */
    isin = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/Asset.PriceTypeEnum} priceType
    */
    priceType = undefined;
    /**
    * @member {String} value
    */
    value = undefined;
    /**
    * @member {module:model/Amount} amount
    */
    amount = undefined;
    /**
    * @member {module:model/Amount} amountAltCurr
    */
    amountAltCurr = undefined;






    /**
    * Allowed values for the <code>priceType</code> property.
    * @enum {String}
    * @readonly
    */
    static PriceTypeEnum = {
    
        /**
         * value: "MRKT"
         * @const
         */
        "MRKT": "MRKT",
    
        /**
         * value: "INDC"
         * @const
         */
        "INDC": "INDC"    
    };



}


