/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Amount from './Amount';





/**
* The Balance model module.
* @module model/Balance
* @version 2.1.0
*/
export default class Balance {
    /**
    * Constructs a new <code>Balance</code>.
    * @alias module:model/Balance
    * @class
    * @param amount {module:model/Amount} Balance amount
    * @param _date {Date} Date of balance (ISO 8601: \"yyyy-MM-dd'T'HH:mm:ssX\")
    */

    constructor(amount, _date) {
        

        
        

        this['amount'] = amount;this['date'] = _date;

        
    }

    /**
    * Constructs a <code>Balance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Balance} obj Optional instance to populate.
    * @return {module:model/Balance} The populated <code>Balance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Balance();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * Balance amount
    * @member {module:model/Amount} amount
    */
    amount = undefined;
    /**
    * Date of balance (ISO 8601: \"yyyy-MM-dd'T'HH:mm:ssX\")
    * @member {Date} date
    */
    date = undefined;








}


