/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Access from './Access';
import AccessFieldsMap from './AccessFieldsMap';





/**
* The BankAccess model module.
* @module model/BankAccess
* @version 2.1.0
*/
export default class BankAccess extends Access {
    /**
    * Constructs a new <code>BankAccess</code>.
    * @alias module:model/BankAccess
    * @class
    * @extends module:model/Access
    * @param providerId {String} Identifier of the provider to which this access belongs
    * @param accessFields {module:model/AccessFieldsMap} Authentication data for the given provider as map of InputFieldId to String (e.g., `{\"USERNAME\", \"yourName\"}`)  The fields necessary for the access are determined by the   InputField descriptions of the related provider.
    * @param type {String} Discriminator for subtypes. At the moment only `BankAccess` is supported.
    */

    constructor(providerId, accessFields, type) {
        

        super(providerId, accessFields, type);
        

        

        
    }

    /**
    * Constructs a <code>BankAccess</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BankAccess} obj Optional instance to populate.
    * @return {module:model/BankAccess} The populated <code>BankAccess</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankAccess();

            

            Access.constructFromObject(data, obj);
            

        }
        return obj;
    }









}


