/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AccessDescription from './AccessDescription';
import Provider from './Provider';





/**
* The BankProvider model module.
* @module model/BankProvider
* @version 2.1.0
*/
export default class BankProvider extends Provider {
    /**
    * Constructs a new <code>BankProvider</code>.
    * @alias module:model/BankProvider
    * @class
    * @extends module:model/Provider
    * @param id {String} UUID of this provider. A constant to identify provider even when  e.g. their bank code changes (provided type is BankProvider)
    * @param name {String} Name of this provider e.g. \"Hamburger Bank\"
    * @param location {String} Location of this provider e.g. \"Hamburg\"
    * @param supported {Boolean} Whether this bank is supported by AHOI-API, i.e. whether you can use a connection of this provider.
    * @param type {String} 
    * @param bankCode {String} Bank Code Number (BLZ, national 8 digits)
    * @param bic {String} Business Identifier Code (defined in ISO-9362)
    */

    constructor(id, name, location, supported, type, bankCode, bic) {
        

        super(id, name, location, supported, type);
        

        this['bankCode'] = bankCode;this['bic'] = bic;

        
    }

    /**
    * Constructs a <code>BankProvider</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BankProvider} obj Optional instance to populate.
    * @return {module:model/BankProvider} The populated <code>BankProvider</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankProvider();

            

            Provider.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('bankCode')) {
                obj['bankCode'] = ApiClient.convertToType(data['bankCode'], 'String');
            }
            if (data.hasOwnProperty('bic')) {
                obj['bic'] = ApiClient.convertToType(data['bic'], 'String');
            }
        }
        return obj;
    }

    /**
    * Bank Code Number (BLZ, national 8 digits)
    * @member {String} bankCode
    */
    bankCode = undefined;
    /**
    * Business Identifier Code (defined in ISO-9362)
    * @member {String} bic
    */
    bic = undefined;








}


