/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ChallengeResponse model module.
* @module model/ChallengeResponse
* @version 2.1.0
*/
export default class ChallengeResponse {
    /**
    * Constructs a new <code>ChallengeResponse</code>.
    * @alias module:model/ChallengeResponse
    * @class
    * @param response {String} Contains the challange to be used for task authorization.
    * @param type {String} Only `TanChallengeResponse` is supported.
    */

    constructor(response, type) {
        

        
        

        this['response'] = response;this['type'] = type;

        
    }

    /**
    * Constructs a <code>ChallengeResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChallengeResponse} obj Optional instance to populate.
    * @return {module:model/ChallengeResponse} The populated <code>ChallengeResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChallengeResponse();

            
            
            

            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Contains the challange to be used for task authorization.
    * @member {String} response
    */
    response = undefined;
    /**
    * Only `TanChallengeResponseDto` is supported.
    * @member {String} type
    */
    type = undefined;








}


