/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AdditionalInformation from './AdditionalInformation';





/**
* The Contractor model module.
* @module model/Contractor
* @version 2.1.0
*/
export default class Contractor extends  AdditionalInformation {
    /**
    * Constructs a new <code>Contractor</code>.
    * @alias module:model/Contractor
    * @class
    * @extends module:model/AdditionalInformation
    * @param id {String}
    * @param type {String} Discriminator for subtypes. At the moment only `Category` and `Contractor` are supported.
    */

    constructor(id, type) {
        
        super(id, type);
    }

    /**
    * Constructs a <code>Contractor</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Contractor} obj Optional instance to populate.
    * @return {module:model/Contractor} The populated <code>Contractor</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contractor();

            

            AdditionalInformation.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('contractorId')) {
                obj['contractorId'] = ApiClient.convertToType(data['contractorId'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} contractorId
    */
    contractorId = undefined;








}


