/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ContractDetailsMap model module.
* @module model/ContractDetailsMap
* @version 2.1.0
*/
export default class ContractDetailsMap {
    /**
    * Constructs a new <code>ContractDetailsMap</code>.
    * @alias module:model/ContractDetailsMap
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ContractDetailsMap</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContractDetailsMap} obj Optional instance to populate.
    * @return {module:model/ContractDetailsMap} The populated <code>ContractDetailsMap</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContractDetailsMap();

            
            
            

            if (data.hasOwnProperty('CUSTOMER_NUMBER')) {
                obj['CUSTOMER_NUMBER'] = ApiClient.convertToType(data['CUSTOMER_NUMBER'], 'String');
            }
            if (data.hasOwnProperty('CONTRACT_NUMBER')) {
                obj['CONTRACT_NUMBER'] = ApiClient.convertToType(data['CONTRACT_NUMBER'], 'String');
            }
            if (data.hasOwnProperty('INVOICE_NUMBER')) {
                obj['INVOICE_NUMBER'] = ApiClient.convertToType(data['INVOICE_NUMBER'], 'String');
            }
            if (data.hasOwnProperty('LICENSE_PLATE')) {
                obj['LICENSE_PLATE'] = ApiClient.convertToType(data['LICENSE_PLATE'], 'String');
            }
            if (data.hasOwnProperty('POLICY_NUMBER')) {
                obj['POLICY_NUMBER'] = ApiClient.convertToType(data['POLICY_NUMBER'], 'String');
            }
        }
        return obj;
    }

    /**
    * The customer number corresponding to the contract.
    * @member {String} CUSTOMER_NUMBER
    */
    CUSTOMER_NUMBER = undefined;
    /**
    * The contract number of the contract.
    * @member {String} CONTRACT_NUMBER
    */
    CONTRACT_NUMBER = undefined;
    /**
    * The invoice number corresponding to the contract.
    * @member {String} INVOICE_NUMBER
    */
    INVOICE_NUMBER = undefined;
    /**
    * The license plate corresponding to the contract.
    * @member {String} LICENSE_PLATE
    */
    LICENSE_PLATE = undefined;
    /**
    * The policy number corresponding to the contract.
    * @member {String} POLICY_NUMBER
    */
    POLICY_NUMBER = undefined;








}


