/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Balance from './Balance';





/**
* The Forecast model module.
* @module model/Forecast
* @version 2.1.0
*/
export default class Forecast {
    /**
    * Constructs a new <code>Forecast</code>.
    * @alias module:model/Forecast
    * @class
    * @param forecastBalance {module:model/Balance} Balance forecast
    * @param accountId {String} ID of account to which this entry belongs
    */

    constructor(forecastBalance, accountId) {
        

        
        

        this['forecastBalance'] = forecastBalance;this['accountId'] = accountId;

        
    }

    /**
    * Constructs a <code>Forecast</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Forecast} obj Optional instance to populate.
    * @return {module:model/Forecast} The populated <code>Forecast</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Forecast();

            
            
            

            if (data.hasOwnProperty('forecastBalance')) {
                obj['forecastBalance'] = Balance.constructFromObject(data['forecastBalance']);
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Balance forecast
    * @member {module:model/Balance} forecastBalance
    */
    forecastBalance = undefined;
    /**
    * ID of account to which this entry belongs
    * @member {String} accountId
    */
    accountId = undefined;








}


