/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Balance from './Balance';
import Forecast from './Forecast';
import Transaction from './Transaction';





/**
* The ForecastTransaction model module.
* @module model/ForecastTransaction
* @version 2.1.0
*/
export default class ForecastTransaction extends  Forecast {
    /**
    * Constructs a new <code>ForecastTransaction</code>.
    * @alias module:model/ForecastTransaction
    * @class
    * @implements module:model/Forecast
    * @param forecastBalance {module:model/Balance} Balance forecast
    * @param accountId {String} Id of account this entry belongs to
    * @param transactions {Array.<module:model/Transaction>} List of unappliedTransaction
    */

    constructor(forecastBalance, accountId, transactions) {
        

        
        super(forecastBalance, accountId);

        this['forecastBalance'] = forecastBalance;this['accountId'] = accountId;this['transactions'] = transactions;

        
    }

    /**
    * Constructs a <code>ForecastTransaction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ForecastTransaction} obj Optional instance to populate.
    * @return {module:model/ForecastTransaction} The populated <code>ForecastTransaction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForecastTransaction();

            
            
            Forecast.constructFromObject(data, obj);

            if (data.hasOwnProperty('forecastBalance')) {
                obj['forecastBalance'] = Balance.constructFromObject(data['forecastBalance']);
            }
            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [Transaction]);
            }
        }
        return obj;
    }

    /**
    * Balance forecast
    * @member {module:model/Balance} forecastBalance
    */
    forecastBalance = undefined;
    /**
    * Id of account this entry belongs to
    * @member {String} accountId
    */
    accountId = undefined;
    /**
    * List of unappliedTransaction
    * @member {Array.<module:model/Transaction>} transactions
    */
    transactions = undefined;


    // Implement Forecast interface:
    /**
    * Balance forecast
    * @member {module:model/Balance} forecastBalance
    */
    forecastBalance = undefined;
/**
    * ID of account to which this entry belongs
    * @member {String} accountId
    */
    accountId = undefined;







}


