/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The JwkJwkPublicKey model module.
* @module model/JwkJwkPublicKey
* @version 2.1.0
*/
export default class JwkJwkPublicKey {
    /**
    * Constructs a new <code>JwkJwkPublicKey</code>.
    * @alias module:model/JwkJwkPublicKey
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>JwkJwkPublicKey</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JwkJwkPublicKey} obj Optional instance to populate.
    * @return {module:model/JwkJwkPublicKey} The populated <code>JwkJwkPublicKey</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JwkJwkPublicKey();

            
            
            

            if (data.hasOwnProperty('kty')) {
                obj['kty'] = ApiClient.convertToType(data['kty'], 'String');
            }
            if (data.hasOwnProperty('alg')) {
                obj['alg'] = ApiClient.convertToType(data['alg'], 'String');
            }
            if (data.hasOwnProperty('n')) {
                obj['n'] = ApiClient.convertToType(data['n'], 'String');
            }
            if (data.hasOwnProperty('e')) {
                obj['e'] = ApiClient.convertToType(data['e'], 'String');
            }
            if (data.hasOwnProperty('kid')) {
                obj['kid'] = ApiClient.convertToType(data['kid'], 'String');
            }
        }
        return obj;
    }

    /**
    * Key type, in this context RSA only
    * @member {String} kty
    */
    kty = undefined;
    /**
    * Algorithm, in this context RSA-OAEP (RSA_2048_SHA1) only.
    * @member {String} alg
    */
    alg = undefined;
    /**
    * Public key modulus BigInteger as base64url encoded
    * @member {String} n
    */
    n = undefined;
    /**
    * Public key exponent BigInteger as base64url encoded
    * @member {String} e
    */
    e = undefined;
    /**
    * Public key ID, i.e. a random UUID per key
    * @member {String} kid
    */
    kid = undefined;








}


