/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SelfDescribedValue from './SelfDescribedValue';





/**
* The RegistrationPublicKey model module.
* @module model/RegistrationPublicKey
* @version 2.1.0
*/
export default class RegistrationPublicKey {
    /**
    * Constructs a new <code>RegistrationPublicKey</code>.
    * @alias module:model/RegistrationPublicKey
    * @class
    * @param keyId {String} api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.keyId.description
    * @param validUntil {String} api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.validUntil.description
    * @param publicKey {module:model/SelfDescribedValue} api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.publicKey.description
    * @param publicKeySignature {module:model/SelfDescribedValue} api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.publicKeySignature.description
    */

    constructor(keyId, validUntil, publicKey, publicKeySignature) {
        

        
        

        this['keyId'] = keyId;this['validUntil'] = validUntil;this['publicKey'] = publicKey;this['publicKeySignature'] = publicKeySignature;

        
    }

    /**
    * Constructs a <code>RegistrationPublicKey</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RegistrationPublicKey} obj Optional instance to populate.
    * @return {module:model/RegistrationPublicKey} The populated <code>RegistrationPublicKey</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistrationPublicKey();

            
            
            

            if (data.hasOwnProperty('keyId')) {
                obj['keyId'] = ApiClient.convertToType(data['keyId'], 'String');
            }
            if (data.hasOwnProperty('validUntil')) {
                obj['validUntil'] = ApiClient.convertToType(data['validUntil'], 'String');
            }
            if (data.hasOwnProperty('publicKey')) {
                obj['publicKey'] = SelfDescribedValue.constructFromObject(data['publicKey']);
            }
            if (data.hasOwnProperty('publicKeySignature')) {
                obj['publicKeySignature'] = SelfDescribedValue.constructFromObject(data['publicKeySignature']);
            }
        }
        return obj;
    }

    /**
    * api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.keyId.description
    * @member {String} keyId
    */
    keyId = undefined;
    /**
    * api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.validUntil.description
    * @member {String} validUntil
    */
    validUntil = undefined;
    /**
    * api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.publicKey.description
    * @member {module:model/SelfDescribedValue} publicKey
    */
    publicKey = undefined;
    /**
    * api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationPublicKeyDto.properties.publicKeySignature.description
    * @member {module:model/SelfDescribedValue} publicKeySignature
    */
    publicKeySignature = undefined;








}


