/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RegistrationResponse model module.
* @module model/RegistrationResponse
* @version 2.1.0
*/
export default class RegistrationResponse {
    /**
    * Constructs a new <code>RegistrationResponse</code>.
    * @alias module:model/RegistrationResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RegistrationResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RegistrationResponse} obj Optional instance to populate.
    * @return {module:model/RegistrationResponse} The populated <code>RegistrationResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegistrationResponse();

            
            
            

            if (data.hasOwnProperty('installation')) {
                obj['installation'] = ApiClient.convertToType(data['installation'], 'String');
            }
        }
        return obj;
    }

    /**
    * api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationResponseDto.properties.installation.description
    * @member {String} installation
    */
    installation = undefined;








}


