/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ResponseObjectMap model module.
* @module model/ResponseObjectMap
* @version 2.1.0
*/
export default class ResponseObjectMap {
    /**
    * Constructs a new <code>ResponseObjectMap</code>.
    * @alias module:model/ResponseObjectMap
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ResponseObjectMap</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ResponseObjectMap} obj Optional instance to populate.
    * @return {module:model/ResponseObjectMap} The populated <code>ResponseObjectMap</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseObjectMap();

            
            
            

            if (data.hasOwnProperty('USERNAME')) {
                obj['USERNAME'] = ApiClient.convertToType(data['USERNAME'], 'String');
            }
            if (data.hasOwnProperty('CUSTOMERNUMBER')) {
                obj['CUSTOMERNUMBER'] = ApiClient.convertToType(data['CUSTOMERNUMBER'], 'String');
            }
            if (data.hasOwnProperty('PIN')) {
                obj['PIN'] = ApiClient.convertToType(data['PIN'], 'String');
            }
            if (data.hasOwnProperty('TAN')) {
                obj['TAN'] = ApiClient.convertToType(data['TAN'], 'String');
            }
        }
        return obj;
    }

    /**
    * The username for the authorization.
    * @member {String} USERNAME
    */
    USERNAME = undefined;
    /**
    * The username for the authorization.
    * @member {String} CUSTOMERNUMBER
    */
    CUSTOMERNUMBER = undefined;
    /**
    * The PIN for the authorization
    * @member {String} PIN
    */
    PIN = undefined;
    /**
    * The TAN for the authorization.
    * @member {String} TAN
    */
    TAN = undefined;








}


