/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Amount from './Amount';





/**
* The Security model module.
* @module model/Security
* @version 2.1.0
*/
export default class Security {
    /**
    * Constructs a new <code>Security</code>.
    * @alias module:model/Security
    * @class
    * @param id {String} Internal ID of this security (generated value)
    */

    constructor(id) {
        

        
        

        this['id'] = id;

        
    }

    /**
    * Constructs a <code>Security</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Security} obj Optional instance to populate.
    * @return {module:model/Security} The populated <code>Security</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Security();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('wkn')) {
                obj['wkn'] = ApiClient.convertToType(data['wkn'], 'String');
            }
            if (data.hasOwnProperty('isin')) {
                obj['isin'] = ApiClient.convertToType(data['isin'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = Amount.constructFromObject(data['price']);
            }
            if (data.hasOwnProperty('priceSource')) {
                obj['priceSource'] = ApiClient.convertToType(data['priceSource'], 'String');
            }
            if (data.hasOwnProperty('quotationDate')) {
                obj['quotationDate'] = ApiClient.convertToType(data['quotationDate'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('priceQualifier')) {
                obj['priceQualifier'] = ApiClient.convertToType(data['priceQualifier'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('amountDivCurr')) {
                obj['amountDivCurr'] = Amount.constructFromObject(data['amountDivCurr']);
            }
            if (data.hasOwnProperty('acquisitionDate')) {
                obj['acquisitionDate'] = ApiClient.convertToType(data['acquisitionDate'], 'String');
            }
            if (data.hasOwnProperty('acquisitionPrice')) {
                obj['acquisitionPrice'] = Amount.constructFromObject(data['acquisitionPrice']);
            }
            if (data.hasOwnProperty('dueDate')) {
                obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'String');
            }
        }
        return obj;
    }

    /**
    * Internal ID of this security (generated value)
    * @member {String} id
    */
    id = undefined;
    /**
    * Wertpapierkennnummer  (german) securities identification number
    * @member {String} wkn
    */
    wkn = undefined;
    /**
    * International Securities Identification Number
    * @member {String} isin
    */
    isin = undefined;
    /**
    * Name
    * @member {String} name
    */
    name = undefined;
    /**
    * Price
    * @member {module:model/Amount} price
    */
    price = undefined;
    /**
    * Source of price   **LMAR - Local Market**   Source of price quotation is the market.     **THEO -Theoretical**   Source of price quotation is a theoretical value based on the market yield.     **VEND- Vendor**   Source of price quotation is an external vendor.
    * @member {module:model/Security.PriceSourceEnum} priceSource
    */
    priceSource = undefined;
    /**
    * @member {String} quotationDate
    */
    quotationDate = undefined;
    /**
    * Market name/location if **priceSource** is *LMAR*
    * @member {String} location
    */
    location = undefined;
    /**
    * Price qualifier    **MRKT** - Market Price   Last reported/known price of a financial instrument in a market.    **INDC** - Indicative Price   Estimated price, for example, for valuation purposes.
    * @member {module:model/Security.PriceQualifierEnum} priceQualifier
    */
    priceQualifier = undefined;
    /**
    * Balance
    * @member {String} quantity
    */
    quantity = undefined;
    /**
    * Holding Value
    * @member {module:model/Amount} amount
    */
    amount = undefined;
    /**
    * Holding Value in divergent currency
    * @member {module:model/Amount} amountDivCurr
    */
    amountDivCurr = undefined;
    /**
    * Acquisition date
    * @member {String} acquisitionDate
    */
    acquisitionDate = undefined;
    /**
    * Acquisition price
    * @member {module:model/Amount} acquisitionPrice
    */
    acquisitionPrice = undefined;
    /**
    * Due date
    * @member {String} dueDate
    */
    dueDate = undefined;






    /**
    * Allowed values for the <code>priceSource</code> property.
    * @enum {String}
    * @readonly
    */
    static PriceSourceEnum = {
    
        /**
         * value: "LMAR"
         * @const
         */
        "LMAR": "LMAR",
    
        /**
         * value: "THEO"
         * @const
         */
        "THEO": "THEO",
    
        /**
         * value: "VEND"
         * @const
         */
        "VEND": "VEND"    
    };

    /**
    * Allowed values for the <code>priceQualifier</code> property.
    * @enum {String}
    * @readonly
    */
    static PriceQualifierEnum = {
    
        /**
         * value: "MRKT"
         * @const
         */
        "MRKT": "MRKT",
    
        /**
         * value: "INDC"
         * @const
         */
        "INDC": "INDC"    
    };



}


