/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ChallengeResponse from './ChallengeResponse';





/**
* The TanChallengeResponse model module.
* @module model/TanChallengeResponse
* @version 2.1.0
*/
export default class TanChallengeResponse extends ChallengeResponse {
    /**
    * Constructs a new <code>TanChallengeResponse</code>.
    * @alias module:model/TanChallengeResponse
    * @class
    * @extends module:model/ChallengeResponse
    * @param response {String} Contains the challange to be used for task authorization.
    * @param type {String} Only `TanChallengeResponse` is supported.
    */

    constructor(response, type) {
        
        super(response, type);
    }

    /**
    * Constructs a <code>TanChallengeResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TanChallengeResponse} obj Optional instance to populate.
    * @return {module:model/TanChallengeResponse} The populated <code>TanChallengeResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TanChallengeResponse();

            

            ChallengeResponse.constructFromObject(data, obj);
            

        }
        return obj;
    }









}


