/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TanMedia model module.
* @module model/TanMedia
* @version 2.1.0
*/
export default class TanMedia {
    /**
    * Constructs a new <code>TanMedia</code>.
    * @alias module:model/TanMedia
    * @class
    * @param tanMediaId {String} ID of this TAN media
    * @param name {String} Name of TANMedia (e.g., \"iTan\")
    * @param description {String} Description of TANMedia (e.g., phone number or card number used for given type)
    */

    constructor(tanMediaId, name, description) {
        

        
        

        this['tanMediaId'] = tanMediaId;this['name'] = name;this['description'] = description;

        
    }

    /**
    * Constructs a <code>TanMedia</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TanMedia} obj Optional instance to populate.
    * @return {module:model/TanMedia} The populated <code>TanMedia</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TanMedia();

            
            
            

            if (data.hasOwnProperty('tanMediaId')) {
                obj['tanMediaId'] = ApiClient.convertToType(data['tanMediaId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * ID of this TAN media
    * @member {String} tanMediaId
    */
    tanMediaId = undefined;
    /**
    * Name of TANMedia (e.g., \"iTan\")
    * @member {String} name
    */
    name = undefined;
    /**
    * Description of TANMedia (e.g., phone number or card number used for given type)
    * @member {String} description
    */
    description = undefined;








}


