/**
 * 
 * [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik
 *
 * OpenAPI spec version: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Task model module.
* @module model/Task
* @version 2.1.0
*/
export default class Task {
    /**
    * Constructs a new <code>Task</code>.
    * @alias module:model/Task
    * @class
    * @param type {String} Discriminator for subtypes. At the moment only `TransferTask` is supported.
    */

    constructor(type) {
        

        
        

        this['type'] = type;

        
    }

    /**
    * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Task} obj Optional instance to populate.
    * @return {module:model/Task} The populated <code>Task</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Task();

            
            
            

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Represents the state of this task.
    * @member {module:model/Task.StateEnum} state
    */
    state = undefined;
    /**
    * UUID of this task to be used for identification on further task actions.
    * @member {String} id
    */
    id = undefined;
    /**
    * Discriminator for subtypes. At the moment only `TransferTask` is supported.
    * @member {String} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>state</code> property.
    * @enum {String}
    * @readonly
    */
    static StateEnum = {
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN": "UNKNOWN",
    
        /**
         * value: "INITIAL"
         * @const
         */
        "INITIAL": "INITIAL",
    
        /**
         * value: "DONE"
         * @const
         */
        "DONE": "DONE",
    
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED": "FAILED",
    
        /**
         * value: "AUTHORIZATION_PENDING"
         * @const
         */
        "AUTHORIZATION_PENDING": "AUTHORIZATION_PENDING",
    
        /**
         * value: "AUTHORIZATION_WRONG"
         * @const
         */
        "AUTHORIZATION_WRONG": "AUTHORIZATION_WRONG"    
    };



}


